# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("background:black;\n"
"color:white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.name_1.setGeometry(QtCore.QRect(410, 0, 271, 21))
        self.name_1.setStyleSheet("text-align: center;")
        self.name_1.setObjectName("name_1")
        self.text = QtWidgets.QTextEdit(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(10, 0, 381, 551))
        self.text.setStyleSheet("border:2px solid white;")
        self.text.setObjectName("text")
        self.notes = QtWidgets.QListWidget(self.centralwidget)
        self.notes.setGeometry(QtCore.QRect(410, 30, 271, 171))
        self.notes.setStyleSheet("border:2px solid white;")
        self.notes.setObjectName("notes")
        self.create_notes = QtWidgets.QPushButton(self.centralwidget)
        self.create_notes.setGeometry(QtCore.QRect(410, 220, 75, 23))
        self.create_notes.setStyleSheet("border:2px solid white;\n"
"border-radius: 5px;")
        self.create_notes.setObjectName("create_notes")
        self.delete_notes = QtWidgets.QPushButton(self.centralwidget)
        self.delete_notes.setGeometry(QtCore.QRect(610, 220, 75, 23))
        self.delete_notes.setStyleSheet("border:2px solid white;\n"
"border-radius: 5px;")
        self.delete_notes.setObjectName("delete_notes")
        self.save_note = QtWidgets.QPushButton(self.centralwidget)
        self.save_note.setGeometry(QtCore.QRect(510, 220, 75, 23))
        self.save_note.setStyleSheet("border:2px solid white;\n"
"border-radius: 5px;")
        self.save_note.setObjectName("save_note")
        self.name_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.name_2.setGeometry(QtCore.QRect(410, 260, 271, 21))
        self.name_2.setObjectName("name_2")
        self.search_tags = QtWidgets.QLineEdit(self.centralwidget)
        self.search_tags.setGeometry(QtCore.QRect(410, 479, 271, 31))
        self.search_tags.setObjectName("search_tags")
        self.creat_tags = QtWidgets.QPushButton(self.centralwidget)
        self.creat_tags.setGeometry(QtCore.QRect(410, 520, 75, 23))
        self.creat_tags.setStyleSheet("border:2px solid white;\n"
"border-radius: 5px;")
        self.creat_tags.setObjectName("creat_tags")
        self.save_tegs = QtWidgets.QPushButton(self.centralwidget)
        self.save_tegs.setGeometry(QtCore.QRect(510, 520, 75, 23))
        self.save_tegs.setStyleSheet("border:2px solid white;\n"
"border-radius: 5px;")
        self.save_tegs.setObjectName("save_tegs")
        self.delete_tag = QtWidgets.QPushButton(self.centralwidget)
        self.delete_tag.setGeometry(QtCore.QRect(610, 520, 75, 23))
        self.delete_tag.setStyleSheet("border:2px solid white;\n"
"border-radius: 5px;")
        self.delete_tag.setObjectName("delete_tag")
        self.notes_2 = QtWidgets.QListWidget(self.centralwidget)
        self.notes_2.setGeometry(QtCore.QRect(410, 290, 271, 171))
        self.notes_2.setStyleSheet("border:2px solid white;")
        self.notes_2.setObjectName("notes_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 696, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EASY FACKING EDITOR BITCH"))
        self.name_1.setText(_translate("MainWindow", "                                    LIST NOTES"))
        self.text.setPlaceholderText(_translate("MainWindow", "text"))
        self.create_notes.setText(_translate("MainWindow", "CREATE"))
        self.delete_notes.setText(_translate("MainWindow", "DELETE"))
        self.save_note.setText(_translate("MainWindow", "SAVE"))
        self.name_2.setText(_translate("MainWindow", "                                    LIST TEGS"))
        self.search_tags.setPlaceholderText(_translate("MainWindow", "search tegs..."))
        self.creat_tags.setText(_translate("MainWindow", "CREATE"))
        self.save_tegs.setText(_translate("MainWindow", "SAVE"))
        self.delete_tag.setText(_translate("MainWindow", "DELETE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
